export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";


export const  SET_MESSAGE = "SET_MESSAGE";
export const  CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";

export const ADD_POST = "ADD_POST";
export const EDIT_POST = "EDIT_POST";
export const DELETE_POST = "DELETE_POST";
export const SEARCH_POST = "SEARCH_POST";

export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL";

export const ADD_COMMENT = "ADD_COMMENT";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

export const GET_FOLLOWING_USERS = "GET_FOLLOWING_USERS";
export const ADD_FOLLOWING_USER = "ADD_FOLLOWING_USER";
export const DELETE_FOLLOWING_USER = "DELETE_FOLLOWING_USER";

export const GET_ALL_USERS = "GET_ALL_USERS";




